### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jean553** [allan-simon/allan-docker-dev-python#5]
Could you please add an official open-source license to your project ? I need some lines :). Thanks!

**Comment by amartens1** [comment]
Indeed, we cannot use your work in business environments without a license clarification

**Comment by allan-simon** [comment]
@amartens1  here you are, a nice and clean MIT license, can't do more permissive :)  if you modify it at softbank (or some of the other libraries I contributed on my freetime, like kibana-logger which i know has been modified),  I would greatly appreciate people propose patch upstream , even if you keep a copy locally.

**Comment by amartens1** [comment]
Thank you very much indeed, I appreciate that. I'll do my best to remind my colleagues to propose their fixes/improvements as far as possible.
KR
